### ISSUE TITLE
Report cluster_version and cluster_infrastructure_provider metrics from within a ROKS cluster

### ISSUE THREAD

**Issue by csrwng** [openshift/hypershift-toolkit#186]
The kube-apiserver operator performs this function for a self-hosted cluster.
We need something to take its place in a ROKS cluster:
https://github.com/openshift/cluster-kube-apiserver-operator/blob/c7b1e077d913fbe6e89d4c10312346234e31e4e4/pkg/operator/configmetrics/configmetrics.go#L20

**Comment by rtheis** [comment]
@csrwng Can you please move this issue to the ROKS toolkit repo if it is still applicable?  Thanks.

**Comment by csrwng** [comment]
done, thx!
