### ISSUE TITLE
Synchronize clusteroperator resources for control plane components to target cluster

### ISSUE THREAD

**Issue by csrwng** [openshift/hypershift-toolkit#67]
clusteroperator resources are needed to report on the version of control plane components. We should synchronize status from the control plane to the clusteroperator resources in the target cluster to make status and version information visible to the end user.

**Comment by rtheis** [comment]
The original problem still exists.  Namely, `oc version` still doesn't not return the OpenShift server version.

**Comment by rtheis** [comment]
My bad, we are good here:

```
$ /usr/local/bin/oc-v4.3 version
Client Version: 4.3.3
Server Version: 4.3.5
Kubernetes Version: v1.16.2
```
